export const TYPE_ARRAY = 'array';
export const TYPE_BOOLEAN = 'boolean';
export const TYPE_INTEGER = 'integer';
export const TYPE_NUMBER = 'number';
export const TYPE_NULL = 'null';
export const TYPE_OBJECT = 'object';
export const TYPE_STRING = 'string';

export const TYPES = [TYPE_ARRAY, TYPE_BOOLEAN, TYPE_INTEGER, TYPE_NUMBER, TYPE_NULL, TYPE_OBJECT, TYPE_STRING];

export const SHOULD_WORK_REQUIRED = 'Err001';
export const SHOULD_WORK_TYPE_ARRAY = 'SHOULD_WORK_TYPE_ARRAY';
export const SHOULD_WORK_TYPE_ARRAY_MAX_ITEMS = 'SHOULD_WORK_TYPE_ARRAY_MAX_ITEMS';
export const SHOULD_WORK_TYPE_ARRAY_MIN_ITEMS = 'SHOULD_WORK_TYPE_ARRAY_MIN_ITEMS';
export const SHOULD_WORK_TYPE_ARRAY_UNIQUE_ITEMS = 'SHOULD_WORK_TYPE_ARRAY_UNIQUE_ITEMS';
export const SHOULD_WORK_TYPE_BOOLEAN = 'Err400';
export const SHOULD_WORK_TYPE_INTEGER = 'Err101';
export const SHOULD_WORK_TYPE_NUMBER = 'Err100';
export const SHOULD_WORK_TYPE_NUMBER_MAXIMUM = 'Err103';
export const SHOULD_WORK_TYPE_NUMBER_MINIMUM = 'Err102';
export const SHOULD_WORK_TYPE_NULL = 'SHOULD_WORK_TYPE_NULL';
export const SHOULD_WORK_TYPE_OBJECT = 'Err500';
export const SHOULD_WORK_TYPE_STRING = 'Err200';
export const SHOULD_WORK_TYPE_STRING_LENGTH = 'Err205';
export const SHOULD_WORK_TYPE_STRING_MAX_LENGTH = 'Err204';
export const SHOULD_WORK_TYPE_STRING_MIN_LENGTH = 'Err203';
export const SHOULD_WORK_TYPE_STRING_FORMAT = 'Err206';
export const SHOULD_WORK_TYPE_STRING_ENUM = 'Err002';
export const SHOULD_WORK_TYPE = {
  array: SHOULD_WORK_TYPE_ARRAY,
  boolean: SHOULD_WORK_TYPE_BOOLEAN,
  integer: SHOULD_WORK_TYPE_INTEGER,
  number: SHOULD_WORK_TYPE_NUMBER,
  null: SHOULD_WORK_TYPE_NULL,
  object: SHOULD_WORK_TYPE_OBJECT,
  string: SHOULD_WORK_TYPE_STRING
};
