export const TYPE_ARRAY = 'array';
export const TYPE_BOOLEAN = 'boolean';
export const TYPE_INTEGER = 'integer';
export const TYPE_NUMBER = 'number';
export const TYPE_NULL = 'null';
export const TYPE_OBJECT = 'object';
export const TYPE_STRING = 'string';

export const TYPES = [TYPE_ARRAY, TYPE_BOOLEAN, TYPE_INTEGER, TYPE_NUMBER, TYPE_NULL, TYPE_OBJECT, TYPE_STRING];

export const SHOULD_WORK_REQUIRED = 'SHOULD_WORK_REQUIRED';
export const SHOULD_WORK_TYPE_ARRAY = 'SHOULD_WORK_TYPE_ARRAY';
export const SHOULD_WORK_TYPE_ARRAY_MAX_ITEMS = 'SHOULD_WORK_TYPE_ARRAY_MAX_ITEMS';
export const SHOULD_WORK_TYPE_ARRAY_MIN_ITEMS = 'SHOULD_WORK_TYPE_ARRAY_MIN_ITEMS';
export const SHOULD_WORK_TYPE_ARRAY_UNIQUE_ITEMS = 'SHOULD_WORK_TYPE_ARRAY_UNIQUE_ITEMS';
export const SHOULD_WORK_TYPE_BOOLEAN = 'SHOULD_WORK_TYPE_BOOLEAN';
export const SHOULD_WORK_TYPE_INTEGER = 'SHOULD_WORK_TYPE_INTEGER';
export const SHOULD_WORK_TYPE_NUMBER = 'SHOULD_WORK_TYPE_NUMBER';
export const SHOULD_WORK_TYPE_NUMBER_MAXIMUM = 'SHOULD_WORK_TYPE_NUMBER_MAXIMUM';
export const SHOULD_WORK_TYPE_NUMBER_MINIMUM = 'SHOULD_WORK_TYPE_NUMBER_MINIMUM';
export const SHOULD_WORK_TYPE_NULL = 'SHOULD_WORK_TYPE_NULL';
export const SHOULD_WORK_TYPE_OBJECT = 'SHOULD_WORK_TYPE_OBJECT';
export const SHOULD_WORK_TYPE_STRING = 'SHOULD_WORK_TYPE_STRING';
export const SHOULD_WORK_TYPE_STRING_MAX_LENGTH = 'SHOULD_WORK_TYPE_STRING_MAX_LENGTH';
export const SHOULD_WORK_TYPE_STRING_MIN_LENGTH = 'SHOULD_WORK_TYPE_STRING_MIN_LENGTH';
export const SHOULD_WORK_TYPE_STRING_FORMAT = 'SHOULD_WORK_TYPE_STRING_FORMAT';
export const SHOULD_WORK_TYPE_STRING_ENUM = 'SHOULD_WORK_TYPE_STRING_ENUM';
export const SHOULD_WORK_TYPE = {
  array: SHOULD_WORK_TYPE_ARRAY,
  boolean: SHOULD_WORK_TYPE_BOOLEAN,
  integer: SHOULD_WORK_TYPE_INTEGER,
  number: SHOULD_WORK_TYPE_NUMBER,
  null: SHOULD_WORK_TYPE_NULL,
  object: SHOULD_WORK_TYPE_OBJECT,
  string: SHOULD_WORK_TYPE_STRING
};
